[tool.poetry]
name = "django-tutorial"
version = "0.1.0"
description = ""
authors = ["hirokihiro <hirokihiro117117@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
